# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b55f04523cb6b91e0eab61665c8fefe93bb1bb93bbb26577f3ca4110abdff503f11c2273208459bda547046691a12b5488eb4c6dee97c810e9955fea68f07d

test:
  secret_key_base: 90e46e3597381a4e9cb690eadb9fa360861507c0d45cdd97beed4b5e549d8f852393fbb92a1fc953004d37a68cb55e776bfb5acb6e76e6dd9ec6fc49bdc0c4a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
